"use strict";
(() => {
  const PAGE_SIZE = 12;
  const state = { hotelSlug: "", mode: "types", roomTypeId: null, roomTypeName: "", page: 1, loading: false, requestSequence: 0, controller: null, items: new Map(), selectedRoom: null, idempotencyKey: "", searchTimer: null, modalTrigger: null, scrollY: 0, scrollLockOwner: "", gallery: { room: null, images: [], index: 0 } };
  const $ = (id) => document.getElementById(id);
  const apiBase = () => String(window.APP_RUNTIME_CONFIG?.API_BASE_URL || `${window.location.origin}/api`).replace(/\/+$/, "");
  const roomsApi = () => `${apiBase()}/public/rooms/${encodeURIComponent(state.hotelSlug)}`;
  const str = (value = "") => String(value ?? "");
  const esc = (value = "") => str(value).replace(/[&<>'"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[c]));
  const int = (value, min, max, fallback) => { const number = Number(value); return Number.isSafeInteger(number) ? Math.min(max, Math.max(min, number)) : fallback; };
  const money = (value) => new Intl.NumberFormat(document.documentElement.lang || "en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(Number(value || 0));
  const ymd = (date) => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, "0")}-${String(date.getDate()).padStart(2, "0")}`;
  const addDays = (value, days) => { const date = /^\d{4}-\d{2}-\d{2}$/.test(str(value)) ? new Date(`${value}T00:00:00`) : new Date(value); date.setDate(date.getDate() + days); return date; };
  const safeUrl = (value = "") => { const candidate = str(value).trim(); if (!candidate) return ""; if (candidate.startsWith("/") && !candidate.startsWith("//")) return candidate; try { const parsed = new URL(candidate, location.href); if (!["http:", "https:"].includes(parsed.protocol)) return ""; if (parsed.pathname.includes("/storage/v1/render/image/public/")) { parsed.pathname = parsed.pathname.replace("/storage/v1/render/image/public/", "/storage/v1/object/public/"); parsed.search = ""; } return parsed.href; } catch { return ""; } };

  function status(message = "", tone = "") { $("roomsStatus").textContent = message; $("roomsStatus").dataset.tone = tone; }
  function formState() { return { checkInDate: $("roomsCheckIn").value, checkOutDate: $("roomsCheckOut").value, adults: int($("roomsAdults").value, 1, 20, 1), children: int($("roomsChildren").value, 0, 20, 0), search: $("roomsSearch").value.trim(), sort: $("roomsSort").value || "recommended", minPrice: $("roomsMinPrice").value.trim(), maxPrice: $("roomsMaxPrice").value.trim(), amenity: $("roomsAmenity").value.trim(), bedType: $("roomsBedType").value.trim(), floor: $("roomsFloor").value.trim() }; }
  function queryFor(page = state.page) { const values = formState(); const params = new URLSearchParams({ hotel: state.hotelSlug, mode: state.mode, page: String(page), pageSize: String(PAGE_SIZE), checkInDate: values.checkInDate, checkOutDate: values.checkOutDate, adults: String(values.adults), children: String(values.children), sort: values.sort }); if (state.roomTypeId && state.mode === "rooms") params.set("roomTypeId", state.roomTypeId); ["search", "minPrice", "maxPrice", "amenity", "bedType", "floor"].forEach((key) => { if (values[key]) params.set(key, values[key]); }); return params; }
  function homeLinks() { const v = formState(); const params = new URLSearchParams({ hotel: state.hotelSlug, checkInDate: v.checkInDate, checkOutDate: v.checkOutDate, adults: v.adults, children: v.children }); const url = `index.html?${params}#rooms`; $("roomsHotelHome").href = url; $("roomsBackHome").href = url; $("roomsMobileSummary").textContent = `${v.checkInDate} → ${v.checkOutDate} · ${v.adults} adult${v.adults === 1 ? "" : "s"}${v.children ? ` · ${v.children} child${v.children === 1 ? "" : "ren"}` : ""}`; }
  function historySync(push = false) { const url = `${location.pathname}?${queryFor()}`; history[push ? "pushState" : "replaceState"]({ page: state.page, mode: state.mode, roomTypeId: state.roomTypeId, scrollY: scrollY }, "", url); homeLinks(); }
  function hydrateForms() { const p = new URLSearchParams(location.search); const today = ymd(new Date()); $("roomsCheckIn").min = today; $("roomsCheckIn").value = p.get("checkInDate") || today; $("roomsCheckOut").min = ymd(addDays($("roomsCheckIn").value, 1)); $("roomsCheckOut").value = p.get("checkOutDate") || ymd(addDays(new Date(), 1)); if ($("roomsCheckOut").value <= $("roomsCheckIn").value) $("roomsCheckOut").value = ymd(addDays($("roomsCheckIn").value, 1)); $("roomsAdults").value = int(p.get("adults"), 1, 20, 1); $("roomsChildren").value = int(p.get("children"), 0, 20, 0); $("roomsSearch").value = str(p.get("search")).slice(0, 80); $("roomsSort").value = ["recommended", "price_asc", "price_desc", "capacity"].includes(p.get("sort")) ? p.get("sort") : "recommended"; ["minPrice", "maxPrice", "amenity", "bedType", "floor"].forEach((key) => { $(`rooms${key[0].toUpperCase()}${key.slice(1)}`).value = str(p.get(key)).slice(0, 80); }); state.roomTypeId = int(p.get("roomTypeId"), 1, Number.MAX_SAFE_INTEGER, null); state.mode = p.get("mode") === "rooms" || state.roomTypeId ? "rooms" : "types"; state.page = int(p.get("page"), 1, 1000, 1); $("roomsSearchClear").hidden = !$("roomsSearch").value; homeLinks(); }
  function modeUi() { const rooms = state.mode === "rooms"; $("roomsResultsEyebrow").textContent = rooms ? "Available Inventory" : "Curated Stays"; $("roomsResultsTitle").textContent = rooms ? state.roomTypeName || "Available Rooms" : "Explore Room Types"; $("roomsBackToTypes").hidden = !rooms; document.querySelectorAll(".rooms-physical-filter").forEach((el) => { el.hidden = !rooms; }); }
  function imageHtml(image, alt, index) { const card = safeUrl(image?.cardUrl); const thumb = safeUrl(image?.thumbnailUrl) || card; if (!card) return '<span class="rooms-discovery-placeholder" aria-hidden="true"><i class="fas fa-bed"></i></span>'; return `<img src="${esc(card)}" srcset="${esc(thumb)} 400w, ${esc(card)} 800w" sizes="(max-width:600px) calc(100vw - 36px), (max-width:1100px) 45vw, 310px" alt="${esc(image.alt || alt)}" width="${Number(image.width || 960)}" height="${Number(image.height || 640)}" loading="${index < 2 ? "eager" : "lazy"}" ${index === 0 ? 'fetchpriority="high"' : ""} decoding="async" referrerpolicy="no-referrer">`; }
  function typeCard(item, index) { const cap = item.capacity || {}; const amenities = Array.isArray(item.amenities) ? item.amenities.slice(0, 3) : []; return `<article class="rooms-discovery-card" data-result-ref="${esc(item.reference)}"><button class="rooms-discovery-media" type="button" data-select-room-type="${Number(item.roomTypeId)}" aria-label="View available ${esc(item.name)} rooms">${imageHtml(item.primaryImage, item.name, index)}<span class="rooms-availability-badge" data-state="${esc(item.availabilityStatus)}">${Number(item.availableCount || 0)} available</span></button><div class="rooms-card-body"><p class="rooms-card-kicker">Room Type</p><div class="rooms-card-title-row"><h3>${esc(item.name)}</h3><div class="rooms-card-price">${esc(money(item.startingPrice))}<small>from / night</small></div></div><div class="rooms-card-meta"><span>Up to ${Number(cap.adults || 0)} adults${Number(cap.children || 0) ? ` · ${Number(cap.children)} children` : ""}</span></div><p class="rooms-card-description">${esc(item.shortDescription || "A comfortable stay designed for a restful visit.")}</p><div class="rooms-card-amenities">${amenities.map((v) => `<span>${esc(v)}</span>`).join("")}</div><div class="rooms-card-actions"><button class="btn btn-outline" type="button" data-select-room-type="${Number(item.roomTypeId)}">View Rooms</button><button class="btn btn-gold" type="button" data-select-room-type="${Number(item.roomTypeId)}">Check Availability</button></div></div></article>`; }
  function roomCard(item, index) { const cap = item.capacity || {}; const meta = [item.roomNumber ? `Room ${item.roomNumber}` : "", item.floor ? `Floor ${item.floor}` : "", item.bedType, `Up to ${Number(cap.adults || 0)} guests`].filter(Boolean); const amenities = Array.isArray(item.amenities) ? item.amenities.slice(0, 3) : []; return `<article class="rooms-discovery-card" data-result-ref="${esc(item.reference)}"><button class="rooms-discovery-media" type="button" data-room-gallery="${Number(item.id)}" aria-label="Open photos for ${esc(item.name)}">${imageHtml(item.primaryImage, item.name, index)}<span class="rooms-availability-badge">Available</span><span class="rooms-photo-count"><i class="fas fa-images" aria-hidden="true"></i> View photos</span></button><div class="rooms-card-body"><p class="rooms-card-kicker">${esc(item.roomType?.name || "Guest Room")}</p><div class="rooms-card-title-row"><h3>${esc(item.name)}</h3><div class="rooms-card-price">${esc(money(item.startingPrice))}<small>/ night</small></div></div><div class="rooms-card-meta">${meta.map((v) => `<span>${esc(v)}</span>`).join("")}</div><p class="rooms-card-description">${esc(item.shortDescription || "A comfortable room ready for your selected stay.")}</p><div class="rooms-card-amenities">${amenities.map((v) => `<span>${esc(v)}</span>`).join("")}</div><div class="rooms-card-actions"><button class="btn btn-outline" type="button" data-room-gallery="${Number(item.id)}">View Details</button><button class="btn btn-gold" type="button" data-room-book="${Number(item.id)}">Book Now</button></div></div></article>`; }
  function skeletons() { $("roomsCards").innerHTML = Array.from({ length: 6 }, () => '<div class="rooms-skeleton" aria-hidden="true"></div>').join(""); $("roomsCards").setAttribute("aria-busy", "true"); $("roomsResultCount").textContent = "Finding available rooms…"; }
  function emptyHtml() { const v = formState(); const filtered = Boolean(v.search || v.minPrice || v.maxPrice || v.amenity || v.bedType || v.floor); const title = state.mode === "rooms" && !filtered ? "No rooms are available for these dates." : filtered ? "No rooms match your filters." : "Room information is currently unavailable."; const detail = state.mode === "rooms" && !filtered ? "Try different dates or return to all room types." : filtered ? "Clear one or more filters and try again." : "Please contact the hotel for assistance."; return `<div class="rooms-empty"><i class="fas fa-bed" aria-hidden="true"></i><h3>${esc(title)}</h3><p>${esc(detail)}</p></div>`; }
  function render(items, append) { const cards = $("roomsCards"); if (!append) { state.items.clear(); cards.innerHTML = ""; } const unique = items.filter((item) => item?.reference && !state.items.has(item.reference)); unique.forEach((item) => state.items.set(item.reference, item)); if (!append && !unique.length) cards.innerHTML = emptyHtml(); else cards.insertAdjacentHTML("beforeend", unique.map((item, index) => state.mode === "types" ? typeCard(item, index) : roomCard(item, index)).join("")); cards.querySelectorAll("img").forEach((image) => image.addEventListener("error", () => { const replacement = document.createElement("span"); replacement.className = "rooms-discovery-placeholder"; replacement.setAttribute("aria-hidden", "true"); replacement.innerHTML = '<i class="fas fa-bed"></i>'; image.replaceWith(replacement); }, { once: true })); cards.setAttribute("aria-busy", "false"); return unique.length; }
  async function loadPage(page, { append = false, push = false, preserveUrl = false } = {}) { if (state.loading) return false; state.loading = true; state.controller?.abort(); state.controller = new AbortController(); const sequence = ++state.requestSequence; const button = $("roomsLoadMore"); const label = button.querySelector("span"); button.disabled = true; label.textContent = "Loading…"; if (!append) { skeletons(); status(""); } try { const response = await fetch(`${roomsApi()}/discovery?${queryFor(page)}`, { signal: state.controller.signal, credentials: "include" }); const payload = await response.json().catch(() => ({})); if (sequence !== state.requestSequence) return false; if (!response.ok || payload.success === false) throw new Error(payload.message || "Rooms could not be loaded."); state.page = Number(payload.pagination?.page || page); const added = render(Array.isArray(payload.items) ? payload.items : [], append); const total = Number(payload.pagination?.totalItems || 0); $("roomsResultCount").textContent = state.mode === "types" ? `${total} room type${total === 1 ? "" : "s"}` : `${total} room${total === 1 ? "" : "s"} available`; button.hidden = !payload.pagination?.hasMore; label.textContent = state.mode === "types" ? "Load More Room Types" : "Load More Rooms"; modeUi(); if (!preserveUrl) historySync(push); if (payload.scanLimitReached) status("Showing the first 500 matching rooms. Narrow your filters for more precise results."); else if (append && added) status(`${added} more result${added === 1 ? "" : "s"} added.`, "success"); return true; } catch (error) { if (error.name === "AbortError") return false; $("roomsCards").setAttribute("aria-busy", "false"); if (!append) $("roomsCards").innerHTML = '<div class="rooms-empty"><i class="fas fa-circle-exclamation" aria-hidden="true"></i><h3>Rooms could not be loaded.</h3><p>Check your connection and retry.</p><button class="btn btn-outline" type="button" data-retry-rooms>Retry</button></div>'; status(error.message, "error"); button.hidden = true; return false; } finally { if (sequence === state.requestSequence) state.loading = false; button.disabled = false; if (label.textContent === "Loading…") label.textContent = "Load More Rooms"; } }
  async function reload(push = true) { state.page = 1; state.items.clear(); return loadPage(1, { push }); }
  async function restorePages(target, scroll = 0) { state.items.clear(); state.page = 1; if (!await loadPage(1, { preserveUrl: true })) return; for (let page = 2; page <= target; page += 1) await loadPage(page, { append: true, preserveUrl: true }); historySync(false); requestAnimationFrame(() => scrollTo(0, scroll)); }

  function lock(owner, trigger) { if (!state.scrollLockOwner) { state.scrollY = window.scrollY; document.body.style.position = "fixed"; document.body.style.top = `-${state.scrollY}px`; document.body.style.width = "100%"; document.body.classList.add("rooms-modal-open"); } state.scrollLockOwner = owner; state.modalTrigger = trigger || state.modalTrigger; }
  function unlock(owner, focus = true) { if (state.scrollLockOwner !== owner) return; const restoreY = state.scrollY; state.scrollLockOwner = ""; document.body.style.position = ""; document.body.style.top = ""; document.body.style.width = ""; document.body.classList.remove("rooms-modal-open"); window.scrollTo(0, restoreY); if (focus) state.modalTrigger?.focus?.(); }
  function galleryImages(room) { return (Array.isArray(room?.galleryImages) ? room.galleryImages : []).map((image) => ({ full: safeUrl(image.optimizedUrl || image.originalUrl), thumb: safeUrl(image.thumbnailUrl || image.cardUrl || image.optimizedUrl || image.originalUrl), alt: str(image.altText || room.title || room.roomNumber || "Room photo"), caption: str(image.caption) })).filter((image) => image.full); }
  function paintGallery() { const gallery = state.gallery; const current = gallery.images[gallery.index]; const image = $("roomsGalleryImage"); $("roomsGalleryTitle").textContent = gallery.room?.title || gallery.room?.roomType?.name || `Room ${gallery.room?.roomNumber || ""}`; $("roomsGalleryCounter").textContent = `${gallery.index + 1} / ${gallery.images.length}`; $("roomsGalleryCaption").textContent = current.caption || current.alt; $("roomsGalleryLoading").hidden = false; $("roomsGalleryError").hidden = true; $("roomsGalleryStage").setAttribute("aria-busy", "true"); image.classList.remove("is-ready", "is-error"); image.alt = current.alt; image.src = current.full; $("roomsGalleryPrevious").disabled = gallery.images.length < 2; $("roomsGalleryNext").disabled = gallery.images.length < 2; $("roomsGalleryThumbnails").innerHTML = gallery.images.map((item, index) => `<button type="button" role="option" aria-selected="${index === gallery.index}" aria-label="View photo ${index + 1}" data-gallery-index="${index}"><img src="${esc(item.thumb)}" alt="" width="160" height="106" loading="lazy" decoding="async"></button>`).join(""); if (!navigator.connection?.saveData && gallery.images.length > 1) [gallery.index - 1, gallery.index + 1].map((i) => (i + gallery.images.length) % gallery.images.length).forEach((i) => { const preload = new Image(); preload.src = gallery.images[i].full; }); }
  function moveGallery(delta) { if (state.gallery.images.length > 1) { state.gallery.index = (state.gallery.index + delta + state.gallery.images.length) % state.gallery.images.length; paintGallery(); } }
  async function openGallery(roomId, trigger) { status("Loading room details…"); try { const response = await fetch(`${roomsApi()}/rooms/${encodeURIComponent(roomId)}`, { credentials: "include" }); const payload = await response.json().catch(() => ({})); if (!response.ok || !payload.room) throw new Error(payload.message || "Room details could not be loaded."); const images = galleryImages(payload.room); if (!images.length) throw new Error("No room photos are currently available."); state.gallery = { room: payload.room, images, index: 0 }; lock("gallery", trigger); $("roomsGalleryDialog").showModal(); paintGallery(); $("roomsGalleryClose").focus(); status(""); } catch (error) { status(error.message, "error"); } }
  function closeGallery(focus = true) { if ($("roomsGalleryDialog").open) $("roomsGalleryDialog").close(); unlock("gallery", focus); }

  function summaryRoom(id) { return [...state.items.values()].find((item) => item.kind === "room" && Number(item.id) === Number(id)); }
  const BOOKING_FIELD_IDS = ["roomsGuestName", "roomsGuestPhone", "roomsGuestEmail", "roomsGuestNotes"];
  function setBookingFieldError(input, message = "") { const error = $(`${input.id}Error`); input.classList.toggle("is-invalid", Boolean(message)); input.setAttribute("aria-invalid", message ? "true" : "false"); input.setCustomValidity(message); if (error) error.textContent = message; }
  function bookingFieldMessage(input) { const value = str(input.value).trim(); input.setCustomValidity(""); if (input.id === "roomsGuestName") { if (!value) return "Enter the guest name."; if (value.length < 2) return "Guest name must contain at least 2 characters."; } if (input.id === "roomsGuestPhone") { const digits = value.replace(/\D/g, ""); if (!value) return "Enter a phone number."; if (!/^\+?[0-9() .-]+$/.test(value)) return "Use only numbers and common phone symbols."; if (digits.length < 7 || digits.length > 15) return "Enter a valid phone number with 7 to 15 digits."; } if (input.id === "roomsGuestEmail" && value && input.validity.typeMismatch) return "Enter a valid email address."; if (input.id === "roomsGuestNotes" && value.length > 1000) return "Notes cannot exceed 1000 characters."; return ""; }
  function validateBookingField(input) { const message = bookingFieldMessage(input); setBookingFieldError(input, message); return !message; }
  function clearBookingValidation() { BOOKING_FIELD_IDS.forEach((id) => setBookingFieldError($(id), "")); }
  function resetBookingGuestFields() { const form = $("roomsBookingForm"); form.reset(); clearBookingValidation(); if (state.selectedRoom) $("roomsBookingRoomId").value = state.selectedRoom.id; }
  function validateBookingForm() { let firstInvalid = null; BOOKING_FIELD_IDS.forEach((id) => { const input = $(id); input.value = input.value.trim(); if (!validateBookingField(input) && !firstInvalid) firstInvalid = input; }); if (firstInvalid) { firstInvalid.focus(); $("roomsBookingForm").reportValidity(); return false; } return true; }
  function openBooking(room, trigger) { if (!room) return; const v = formState(); if (!v.checkInDate || !v.checkOutDate || v.checkOutDate <= v.checkInDate) { status("Choose valid check-in and check-out dates before booking.", "error"); return $("roomsCheckIn").focus(); } state.selectedRoom = room; state.idempotencyKey = ""; resetBookingGuestFields(); $("roomsBookingRoomId").value = room.id; $("roomsBookingTitle").textContent = room.name || room.title || `Room ${room.roomNumber || ""}`; $("roomsBookingSummary").innerHTML = `<div class="room-booking-summary-row"><span>Dates</span><strong>${esc(v.checkInDate)} to ${esc(v.checkOutDate)}</strong></div><div class="room-booking-summary-row"><span>Guests</span><strong>${v.adults} adult${v.adults === 1 ? "" : "s"}${v.children ? `, ${v.children} child${v.children === 1 ? "" : "ren"}` : ""}</strong></div><div class="room-booking-summary-row"><span>Room</span><strong>${esc(room.name || room.title || room.roomNumber)}</strong></div><div class="room-booking-summary-row"><span>From</span><strong>${esc(money(room.startingPrice || room.pricePerNight))}/night</strong></div>`; $("roomsBookingStatus").textContent = "Final availability and price are confirmed by the hotel before saving."; $("roomsBookingStatus").dataset.tone = "muted"; lock("booking", trigger); $("roomsBookingDialog").showModal(); requestAnimationFrame(() => $("roomsGuestName").focus()); }
  function closeBooking() { if ($("roomsBookingDialog").open) $("roomsBookingDialog").close(); unlock("booking", true); }
  async function submitBooking(event) { event.preventDefault(); const form = $("roomsBookingForm"); if (!state.selectedRoom || !validateBookingForm()) return; const v = formState(); const data = new FormData(form); const payload = { roomId: Number(state.selectedRoom.id), guestName: str(data.get("guestName")).trim(), guestPhone: str(data.get("guestPhone")).trim(), guestEmail: str(data.get("guestEmail")).trim(), notes: str(data.get("notes")).trim(), checkInDate: v.checkInDate, checkOutDate: v.checkOutDate, adults: v.adults, children: v.children }; const button = form.querySelector(".rooms-booking-submit"); const label = button.querySelector("span"); button.disabled = true; label.textContent = "Submitting..."; $("roomsBookingStatus").textContent = "Submitting your booking request securely..."; $("roomsBookingStatus").dataset.tone = "muted"; state.idempotencyKey ||= crypto.randomUUID?.() || `room-${Date.now()}-${Math.random().toString(36).slice(2)}`; try { const response = await fetch(`${roomsApi()}/bookings`, { method: "POST", credentials: "include", headers: { "Content-Type": "application/json", "Idempotency-Key": state.idempotencyKey }, body: JSON.stringify(payload) }); const result = await response.json().catch(() => ({})); if (!response.ok || result.success === false) { const error = new Error(result.message || "Unable to submit booking request."); error.code = result.code; throw error; } const reference = result.booking?.id || "pending confirmation"; state.idempotencyKey = ""; resetBookingGuestFields(); $("roomsBookingStatus").innerHTML = `<i class="fas fa-circle-check" aria-hidden="true"></i><span>Booking request submitted successfully. Reference: ${esc(reference)}. The hotel will contact you to confirm.</span>`; $("roomsBookingStatus").dataset.tone = "success"; await reload(false); } catch (error) { $("roomsBookingStatus").textContent = error.code === "ROOM_ALREADY_BOOKED" ? "This room was just booked for those dates. Please choose another room or date." : error.message; $("roomsBookingStatus").dataset.tone = "error"; } finally { button.disabled = false; label.textContent = "Submit Booking Request"; } }
  function filterDrawer(open) { const panel = document.querySelector(".rooms-filter-panel"); panel.classList.toggle("is-open", open); $("roomsFilterBackdrop").hidden = !open; if (open) { lock("filters", $("roomsFilterOpen")); $("roomsSearch").focus(); } else { unlock("filters", true); } }
  function clearFilters() { $("roomsFilterForm").reset(); $("roomsSort").value = "recommended"; $("roomsSearchClear").hidden = true; reload(true); }
  function bind() {
    $("roomsDiscoveryForm").addEventListener("submit", (event) => { event.preventDefault(); reload(true); });
    $("roomsCheckIn").addEventListener("change", () => { const minimum = ymd(addDays($("roomsCheckIn").value, 1)); $("roomsCheckOut").min = minimum; if ($("roomsCheckOut").value <= $("roomsCheckIn").value) $("roomsCheckOut").value = minimum; homeLinks(); });
    ["roomsCheckOut", "roomsAdults", "roomsChildren"].forEach((id) => $(id).addEventListener("change", homeLinks));
    $("roomsFilterForm").addEventListener("submit", (event) => { event.preventDefault(); filterDrawer(false); reload(true); });
    $("roomsSort").addEventListener("change", () => reload(true));
    $("roomsSearch").addEventListener("input", () => { $("roomsSearchClear").hidden = !$("roomsSearch").value; clearTimeout(state.searchTimer); state.searchTimer = setTimeout(() => reload(true), 350); });
    $("roomsSearchClear").addEventListener("click", () => { $("roomsSearch").value = ""; $("roomsSearchClear").hidden = true; reload(true); });
    $("roomsClearFilters").addEventListener("click", clearFilters);
    $("roomsLoadMore").addEventListener("click", () => { if (!state.loading) loadPage(state.page + 1, { append: true }); });
    $("roomsBackToTypes").addEventListener("click", () => { state.mode = "types"; state.roomTypeId = null; state.roomTypeName = ""; reload(true); });
    $("roomsFilterOpen").addEventListener("click", () => filterDrawer(true)); $("roomsFilterClose").addEventListener("click", () => filterDrawer(false)); $("roomsFilterBackdrop").addEventListener("click", () => filterDrawer(false));
    $("roomsCards").addEventListener("click", (event) => { if (event.target.closest("[data-retry-rooms]")) return void reload(false); const type = event.target.closest("[data-select-room-type]"); if (type) { const item = [...state.items.values()].find((candidate) => Number(candidate.roomTypeId) === Number(type.dataset.selectRoomType)); state.mode = "rooms"; state.roomTypeId = Number(type.dataset.selectRoomType); state.roomTypeName = item?.name || "Available Rooms"; return void reload(true); } const gallery = event.target.closest("[data-room-gallery]"); if (gallery) return void openGallery(Number(gallery.dataset.roomGallery), gallery); const book = event.target.closest("[data-room-book]"); if (book) openBooking(summaryRoom(book.dataset.roomBook), book); });
    $("roomsGalleryClose").addEventListener("click", () => closeGallery()); $("roomsGalleryPrevious").addEventListener("click", () => moveGallery(-1)); $("roomsGalleryNext").addEventListener("click", () => moveGallery(1));
    $("roomsGalleryThumbnails").addEventListener("click", (event) => { const button = event.target.closest("[data-gallery-index]"); if (button) { state.gallery.index = Number(button.dataset.galleryIndex); paintGallery(); } });
    $("roomsGalleryImage").addEventListener("load", () => { $("roomsGalleryLoading").hidden = true; $("roomsGalleryStage").setAttribute("aria-busy", "false"); $("roomsGalleryImage").classList.add("is-ready"); });
    $("roomsGalleryImage").addEventListener("error", () => { $("roomsGalleryLoading").hidden = true; $("roomsGalleryError").hidden = false; $("roomsGalleryStage").setAttribute("aria-busy", "false"); $("roomsGalleryImage").classList.add("is-error"); });
    $("roomsGalleryFullscreen").addEventListener("click", () => $("roomsGalleryDialog").requestFullscreen?.().catch(() => {}));
    $("roomsGalleryBook").addEventListener("click", () => { const room = state.gallery.room; closeGallery(false); openBooking({ id: room.id, name: room.title || room.roomType?.name || `Room ${room.roomNumber}`, roomNumber: room.roomNumber, startingPrice: room.pricePerNight }, state.modalTrigger); });
    $("roomsGalleryDialog").addEventListener("cancel", (event) => { event.preventDefault(); closeGallery(); }); $("roomsGalleryDialog").addEventListener("keydown", (event) => { if (event.key === "ArrowLeft") moveGallery(-1); if (event.key === "ArrowRight") moveGallery(1); });
    $("roomsBookingClose").addEventListener("click", closeBooking); $("roomsBookingDialog").addEventListener("cancel", (event) => { event.preventDefault(); closeBooking(); }); $("roomsBookingForm").addEventListener("submit", submitBooking);
    BOOKING_FIELD_IDS.forEach((id) => { const input = $(id); input.addEventListener("blur", () => validateBookingField(input)); input.addEventListener("input", () => { if (input.getAttribute("aria-invalid") === "true") validateBookingField(input); }); });
    addEventListener("popstate", async (event) => { hydrateForms(); modeUi(); await restorePages(int(event.state?.page, 1, 1000, state.page), Number(event.state?.scrollY || 0)); });
    addEventListener("beforeunload", () => history.replaceState({ ...(history.state || {}), scrollY, page: state.page, mode: state.mode, roomTypeId: state.roomTypeId }, ""));
  }
  async function branding() { try { const response = await fetch(`${apiBase()}/public/hotel/${encodeURIComponent(state.hotelSlug)}`, { credentials: "include" }); const payload = await response.json().catch(() => ({})); const hotel = payload.hotel || {}; const name = str(hotel.name || hotel.hotelName || "Your Hotel").trim(); $("roomsHotelName").textContent = name; $("roomsPageTitle").textContent = `${name} Rooms & Suites`; document.title = `Rooms & Suites · ${name}`; document.querySelector('meta[property="og:title"]')?.setAttribute("content", document.title); const canonical = document.createElement("link"); canonical.rel = "canonical"; canonical.href = `${location.origin}${location.pathname}?hotel=${encodeURIComponent(state.hotelSlug)}`; document.head.append(canonical); } catch { /* optional branding */ } }
  async function init() { try { state.hotelSlug = typeof resolveHotelSlug === "function" ? await resolveHotelSlug() : new URLSearchParams(location.search).get("hotel") || ""; if (!state.hotelSlug) throw new Error("No hotel could be resolved for this Rooms page."); hydrateForms(); modeUi(); bind(); void branding(); const target = state.page; await restorePages(target, Number(history.state?.scrollY || 0)); } catch (error) { $("roomsCards").setAttribute("aria-busy", "false"); $("roomsCards").innerHTML = `<div class="rooms-empty"><i class="fas fa-circle-exclamation" aria-hidden="true"></i><h3>Rooms are unavailable.</h3><p>${esc(error.message || "Please return to the hotel home page and try again.")}</p></div>`; status(error.message, "error"); } finally { document.body.classList.remove("app-booting"); } }
  document.addEventListener("DOMContentLoaded", init, { once: true });
})();
